# Generated by Django 5.0.6 on 2024-06-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detail_description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.PositiveIntegerField()),
                ('action_url', models.URLField(max_length=500)),
                ('logo', models.URLField(max_length=500)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.blog')),
            ],
        ),
    ]
