# Generated by Django 5.0.6 on 2024-06-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0002_categoryfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
