# Generated by Django 5.0.6 on 2024-06-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfeature',
            name='action_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='detail_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='pros',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='review',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
