# Generated by Django 5.0.6 on 2024-06-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0005_alter_categoryfeature_action_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('logo_url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('action_url', models.URLField(max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.blog')),
            ],
        ),
    ]
