# Generated by Django 5.0.6 on 2024-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0006_affiliatelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='orderBy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
