# Generated by Django 5.0.6 on 2024-06-28 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0008_blog_image_blog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='cons',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='detail_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='pros',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
