# Generated by Django 5.0.6 on 2024-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0009_blog_feature_title_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
