# Generated by Django 5.0.6 on 2024-06-29 06:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0010_affiliatelink_status_blog_status_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfeature',
            name='action_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='cons',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='detail_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='pros',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='review',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
