# Generated by Django 5.0.6 on 2024-06-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0011_alter_categoryfeature_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfeature',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
