# Generated by Django 5.0.6 on 2024-06-29 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0012_alter_categoryfeature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
