# Generated by Django 5.0.6 on 2024-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0013_affiliatelink_date_created_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
