# Generated by Django 5.0.6 on 2024-12-06 04:39

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0017_affiliatelink_image_categoryfeature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the page', max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the page', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the page', max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description or content of the page', null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for the page', null=True, upload_to='blog_images/')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the page', null=True, upload_to='background_images/')),
                ('status', models.BooleanField(default=True, help_text='Publish status of the page')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the page was created')),
            ],
            options={
                'verbose_name': 'Site Page',
                'verbose_name_plural': 'Site Pages',
                'ordering': ['-date_created'],
            },
        ),
    ]
