# Generated by Django 5.0.6 on 2024-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0018_sitepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='title',
            field=models.CharField(help_text='Main title of the page', max_length=255),
        ),
    ]
