# Generated by Django 5.0.6 on 2025-01-04 15:16

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0024_alter_category_options_category_orderby_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for the page', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for the page', max_length=500, null=True),
        ),
    ]
